version: '3'

services:
  frontend:
    image: harish492/frontend-image:latest
    ports:
      - "3000:3000"
    networks:
      - my-network

  backend:
    image: harish492/backend-image:latest
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
